### ISSUE TITLE
[BUG] misleading docs

### ISSUE THREAD

**Issue by isvicy** [Storia-AI/sage#107]
**Describe the bug**
https://sage-docs.storia.ai/quality#openai docs here won't work

**To Reproduce**
1. Install `sage` via `pipx install git+https://github.com/Storia-AI/sage.git@main`
2. Run indexing via
 ```
 sage-index Project-HAMi/ascend-device-plugin \
    --mode=remote --embedding-provider=openai --reranker-provider=nvidia
usage: sage-index [-h] [--mode {local,remote}] [--config CONFIG] [--commit-hash COMMIT_HASH] [--local-dir LOCAL_DIR] [--embedding-provider {openai,voyage,marqo,gemini}] [--embedding-model EMBEDDING_MODEL]
                  [--embedding-size EMBEDDING_SIZE] [--tokens-per-chunk TOKENS_PER_CHUNK] [--chunks-per-batch CHUNKS_PER_BATCH] [--max-embedding-jobs MAX_EMBEDDING_JOBS]
                  [--vector-store-provider {pinecone,marqo,chroma,faiss,milvus,qdrant}] [--index-name INDEX_NAME] [--milvus-uri MILVUS_URI] [--index-namespace INDEX_NAMESPACE] [--marqo-url MARQO_URL]
                  [--retrieval-alpha RETRIEVAL_ALPHA] [--retriever-top-k RETRIEVER_TOP_K] [--multi-query-retriever | --no-multi-query-retriever] [--llm-retriever | --no-llm-retriever] [--include INCLUDE]
                  [--exclude EXCLUDE] [--index-repo | --no-index-repo] [--index-issues | --no-index-issues] [--index-issue-comments | --no-index-issue-comments]
                  repo_id
sage-index: error: unrecognized arguments: --reranker-provider=nvidia 
```
the above command is from the offical doc here: https://sage-docs.storia.ai/quality#openai

if we remove the unrecognized argument, then we will meet this:
```
sage-index Project-HAMi/ascend-device-plugin \
    --mode=remote \
    --embedding-provider=openai
Traceback (most recent call last):
  File "/home/isvic/.local/bin/sage-index", line 8, in <module>
    sys.exit(main())
  File "/home/isvic/.local/share/pipx/venvs/storia-sage/lib/python3.10/site-packages/sage/index.py", line 37, in main
    validator(args)
  File "/home/isvic/.local/share/pipx/venvs/storia-sage/lib/python3.10/site-packages/sage/config.py", line 378, in validate_vector_store_args
    raise ValueError(
ValueError: Please set the ANTHROPIC_API_KEY environment variable to use the LLM retriever. (We're constrained to Claude because we need prompt caching.)
```

**Expected behavior**
A clear and concise docs which confirmed work.

**Screenshots**

**Setup (please complete the following information):**
 - Python version: 3.10.14
 - OS:  Linux

**Comment by isvicy** [comment]
i also have tried the cloud version of sage, here is what i got:
![image](https://github.com/user-attachments/assets/ad5b0ca7-d99e-4705-8bac-b57fa2fe630f)
