### ISSUE TITLE
Not able to setup the repo

### ISSUE THREAD

**Issue by Saksham1387** [Storia-AI/sage#33]
After exporting the GITHUB_REPO variable, when I am running the :
r2v-index $GITHUB_REPO
command it is giving me that r2v-index is not a command.Now when i install the setup.py file, it is giving me :
Traceback (most recent call last):
  File "/Users/sakshamchaudhary/Documents/repo2vec/hello/lib/python3.7/site-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/Users/sakshamchaudhary/Documents/repo2vec/hello/lib/python3.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/Users/sakshamchaudhary/Documents/repo2vec/hello/lib/python3.7/site-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/Users/sakshamchaudhary/Documents/repo2vec/hello/lib/python3.7/site-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/var/folders/g2/581g6n5j1tsbywrdg2gxjmlh0000gn/T/easy_install-dfekf5jw/tree_sitter_language_pack-0.2.0/setup.py", line 22, in <module>
    ],
TypeError: 'type' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 35, in <module>
    python_requires=">=3.9",
  File "/Users/sakshamchaudhary/Documents/repo2vec/hello/lib/python3.7/site-packages/setuptools/__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "/Users/sakshamchaudhary/.pyenv/versions/3.7.12/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Users/sakshamchaudhary/.pyenv/versions/3.7.12/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/Users/sakshamchaudhary/.pyenv/versions/3.7.12/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/Users/sakshamchaudhary/Documents/repo2vec/hello/lib/python3.7/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/Users/sakshamchaudhary/Documents/repo2vec/hello/lib/python3.7/site-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.run(show_deprecation=False)
  File "/Users/sakshamchaudhary/Documents/repo2vec/hello/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 424, in run
    self.easy_install(spec, not self.no_deps)
  File "/Users/sakshamchaudhary/Documents/repo2vec/hello/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 673, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/Users/sakshamchaudhary/Documents/repo2vec/hello/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 720, in install_item
    self.process_distribution(spec, dist, deps)
  File "/Users/sakshamchaudhary/Documents/repo2vec/hello/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 765, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/Users/sakshamchaudhary/Documents/repo2vec/hello/lib/python3.7/site-packages/pkg_resources/__init__.py", line 783, in resolve
    replace_conflicting=replace_conflicting
  File "/Users/sakshamchaudhary/Documents/repo2vec/hello/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1066, in best_match
    return self.obtain(req, installer)
  File "/Users/sakshamchaudhary/Documents/repo2vec/hello/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1078, in obtain
    return installer(requirement)
  File "/Users/sakshamchaudhary/Documents/repo2vec/hello/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 692, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/Users/sakshamchaudhary/Documents/repo2vec/hello/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 718, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/Users/sakshamchaudhary/Documents/repo2vec/hello/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 903, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/Users/sakshamchaudhary/Documents/repo2vec/hello/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 1171, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/Users/sakshamchaudhary/Documents/repo2vec/hello/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 1157, in run_setup
    run_setup(setup_script, args)
  File "/Users/sakshamchaudhary/Documents/repo2vec/hello/lib/python3.7/site-packages/setuptools/sandbox.py", line 253, in run_setup
    raise
  File "/Users/sakshamchaudhary/.pyenv/versions/3.7.12/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/sakshamchaudhary/Documents/repo2vec/hello/lib/python3.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/Users/sakshamchaudhary/.pyenv/versions/3.7.12/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/sakshamchaudhary/Documents/repo2vec/hello/lib/python3.7/site-packages/setuptools/sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File "/Users/sakshamchaudhary/Documents/repo2vec/hello/lib/python3.7/site-packages/setuptools/sandbox.py", line 141, in resume
    six.reraise(type, exc, self._tb)
  File "/Users/sakshamchaudhary/Documents/repo2vec/hello/lib/python3.7/site-packages/setuptools/_vendor/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/Users/sakshamchaudhary/Documents/repo2vec/hello/lib/python3.7/site-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/Users/sakshamchaudhary/Documents/repo2vec/hello/lib/python3.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/Users/sakshamchaudhary/Documents/repo2vec/hello/lib/python3.7/site-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/Users/sakshamchaudhary/Documents/repo2vec/hello/lib/python3.7/site-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/var/folders/g2/581g6n5j1tsbywrdg2gxjmlh0000gn/T/easy_install-dfekf5jw/tree_sitter_language_pack-0.2.0/setup.py", line 22, in <module>
    ],
TypeError: 'type' object is not subscriptable

**Comment by iuliaturc** [comment]
Thanks for trying out the repo! Could you please make sure that you're using the latest version (e.g. 0.1.8)? We've renamed the command recently (from `index` to `r2v-index`).

For instance, if you use `pipx install repo2vec==0.1.8`, you should see:

```
installed package repo2vec 0.1.8, installed using Python 3.12.5
  These apps are now globally available
    - r2v-chat
    - r2v-index
done! ✨ 🌟 ✨
```

Then
```
export GITHUB_REPO = ...
r2v-index $GITHUB_REPO
```

**Comment by Saksham1387** [comment]
I did it, but still the urllib3 library version miss match is still not solved.
Collecting urllib3==1.26.20
  Using cached urllib3-1.26.20-py2.py3-none-any.whl.metadata (50 kB)
Using cached urllib3-1.26.20-py2.py3-none-any.whl (144 kB)
Installing collected packages: urllib3
  Attempting uninstall: urllib3
    Found existing installation: urllib3 2.2.2
    Uninstalling urllib3-2.2.2:
      Successfully uninstalled urllib3-2.2.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pinecone-client 5.0.1 requires pinecone-plugin-inference<2.0.0,>=1.0.3, which is not installed.
pinecone-client 5.0.1 requires pinecone-plugin-interface<0.0.8,>=0.0.7, which is not installed.
gradio 4.43.0 requires urllib3~=2.0, but you have urllib3 1.26.20 which is incompatible.
Successfully installed urllib3-1.26.20

The problem here is that marqo and gradio both require different versions of urllib3, please look in to this

**Comment by iuliaturc** [comment]
Hmm we deliberately loosened up the `gradio` version [here](https://github.com/Storia-AI/repo2vec/blob/b3cad71491caecb116c60c2498806adafb0c80b2/requirements.txt#L4) to account for this `urllib3` mismatch.

gradio 4.26 will not cause a mismatch, but I'm seeing that your system is working with a much later version (4.43). I suspect this would happen if you already had gradio installed in your environment from some other project.

Before I investigate further, could you please confirm that you're either using `pipx` or working with a fresh virtual environment? Thanks so much for your patience!

**Comment by mihail911** [comment]
Closing due to inactivity
