### ISSUE TITLE
Breaks on repositories with a dot in the name

### ISSUE THREAD

**Issue by lathiat** [Storia-AI/sage#44]
Hi Team,

I tried to briefly test out sage locally using the README instructions on the GitHub repository https://github.com/openstack/oslo.messaging

It seems the dot in the name is upsetting marqo. You may need to translate the repository name in the case of some special characters:

```
sage-index openstack/oslo.messaging

sage-index openstack/oslo.messaging
INFO:root:Cloning the repository...
INFO:root:Embedding the repo...
Traceback (most recent call last):
  File "/Users/lathiat/Library/Application Support/pipx/venvs/sage/lib/python3.12/site-packages/marqo/_httprequests.py", line 148, in _validate
    request.raise_for_status()
  File "/Users/lathiat/Library/Application Support/pipx/venvs/sage/lib/python3.12/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://localhost:8882/indexes/openstack_oslo.messaging
```

You also see a related error in the Marqo logs

```
ERROR:marqo.api.route:1 validation error for UnstructuredMarqoIndexRequest
name
  "openstack_oslo.messaging" is not a valid index name. Index name must match [a-zA-Z_-][a-zA-Z0-9_-]* and must not start with "marqo__" (type=value_error)
Traceback (most recent call last):
  File "/app/src/marqo/api/route.py", line 20, in marqo_custom_route_handler
    return await original_route_handler(request)
  File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 235, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.8/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/usr/local/lib/python3.8/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/app/src/marqo/tensor_search/api.py", line 250, in create_index
    marqo_config.index_management.create_index(settings.to_marqo_index_request(index_name))
  File "/app/src/marqo/tensor_search/models/index_settings.py", line 174, in to_marqo_index_request
    return UnstructuredMarqoIndexRequest(
  File "/usr/local/lib/python3.8/site-packages/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for UnstructuredMarqoIndexRequest
name
  "openstack_oslo.messaging" is not a valid index name. Index name must match [a-zA-Z_-][a-zA-Z0-9_-]* and must not start with "marqo__" (type=value_error)

```

**Comment by iuliaturc** [comment]
Thanks for flagging this @lathiat!
