### ISSUE TITLE
ValueError: repo_id must be in the format 'owner/repo'

### ISSUE THREAD

**Issue by jatolentino** [Storia-AI/sage#49]
Hello, I got this error after running `sage-chat huggingface-transformers --commit-hash=7bb1c99800d235791dace10305731f377db8077b --mode=remote`

```sh
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\SAGE-TEST\my-venv\Scripts\sage-chat.exe\__main__.py", line 7, in <module>
  File "D:\SAGE-TEST\my-venv\Lib\site-packages\sage\chat.py", line 87, in main
    validator(args)
  File "D:\SAGE-TEST\my-venv\Lib\site-packages\sage\config.py", line 215, in validate_repo_args
    raise ValueError("repo_id must be in the format 'owner/repo'")
ValueError: repo_id must be in the format 'owner/repo'
```

**Comment by mihail911** [comment]
Try using the following command @jatolentino:
`sage-chat huggingface/transformers --commit-hash=7bb1c99800d235791dace10305731f377db8077b --mode=remote`

**Comment by iuliaturc** [comment]
@jatolentino Good catch, that was actually a typo in the Kaggle instructions! Indeed, the hyphen should have been a slash.

**Comment by jatolentino** [comment]
@mihail911 @iuliaturc lol, my bad, I didn't realize about that typo, thanks :). So, I just lunched the gradio interface and tested with a mock question, and everything is working well!

**Comment by iuliaturc** [comment]
Glad to hear! Closing the issue then.
