### ISSUE TITLE
[BUG] Can't pip install the git repo

### ISSUE THREAD

**Issue by mikelueck** [Storia-AI/sage#64]
**Describe the bug**
(sage-venv) mikes-mac-mini:SAGE mikelueck$ pip install git+https://github.com/Storia-AI/sage.git@main
Collecting git+https://github.com/Storia-AI/sage.git@main
  Cloning https://github.com/Storia-AI/sage.git (to revision main) to /private/var/folders/j9/7ytknchx3lj82tlj2tlszm5c0000gn/T/pip-req-build-a5337o0o
  Running command git clone --filter=blob:none --quiet https://github.com/Storia-AI/sage.git /private/var/folders/j9/7ytknchx3lj82tlj2tlszm5c0000gn/T/pip-req-build-a5337o0o
  Resolved https://github.com/Storia-AI/sage.git to commit 0111d6bc9c47fe66f3b7724e0a605910d8bb44fe
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [87 lines of output]
      configuration error: `tool.setuptools.package-data` keys must be named by:
      
          at least one of the following:
            - {type: string, format: 'python-module-name'}
            - {predefined value: '*'}
      
      DESCRIPTION:
          Mapping from package names to lists of glob patterns. Usually this option is
          not needed when using ``include-package-data = true`` For more information
          on how to include data files, check ``setuptools`` `docs
          <https://setuptools.pypa.io/en/latest/userguide/datafiles.html>`_.
      
      GIVEN VALUE:
          {
              "sample-exclude.txt": [
                  "sage"
              ]
          }
      
      OFFENDING RULE: 'propertyNames'
      
      DEFINITION:
          {
              "type": "object",
              "additionalProperties": false,
              "propertyNames": {
                  "anyOf": [
                      {
                          "type": "string",
                          "format": "python-module-name"
                      },
                      {
                          "const": "*"
                      }
                  ]
              },
              "patternProperties": {
                  "^.*$": {
                      "type": "array",
                      "items": {
                          "type": "string"
                      }
                  }
              }
          }
      
      For more details about `format` see
      https://validate-pyproject.readthedocs.io/en/latest/api/validate_pyproject.formats.html
      
      Traceback (most recent call last):
        File "/Users/mikelueck/src/SAGE/sage-venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/mikelueck/src/SAGE/sage-venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/mikelueck/src/SAGE/sage-venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/j9/7ytknchx3lj82tlj2tlszm5c0000gn/T/pip-build-env-j0pur41a/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 332, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/j9/7ytknchx3lj82tlj2tlszm5c0000gn/T/pip-build-env-j0pur41a/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 302, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/j9/7ytknchx3lj82tlj2tlszm5c0000gn/T/pip-build-env-j0pur41a/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 318, in run_setup
          exec(code, locals())
        File "<string>", line 1, in <module>
        File "/private/var/folders/j9/7ytknchx3lj82tlj2tlszm5c0000gn/T/pip-build-env-j0pur41a/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 117, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/j9/7ytknchx3lj82tlj2tlszm5c0000gn/T/pip-build-env-j0pur41a/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 157, in setup
          dist.parse_config_files()
        File "/private/var/folders/j9/7ytknchx3lj82tlj2tlszm5c0000gn/T/pip-build-env-j0pur41a/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 608, in parse_config_files
          pyprojecttoml.apply_configuration(self, filename, ignore_option_errors)
        File "/private/var/folders/j9/7ytknchx3lj82tlj2tlszm5c0000gn/T/pip-build-env-j0pur41a/overlay/lib/python3.12/site-packages/setuptools/config/pyprojecttoml.py", line 71, in apply_configuration
          config = read_configuration(filepath, True, ignore_option_errors, dist)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/j9/7ytknchx3lj82tlj2tlszm5c0000gn/T/pip-build-env-j0pur41a/overlay/lib/python3.12/site-packages/setuptools/config/pyprojecttoml.py", line 139, in read_configuration
          validate(subset, filepath)
        File "/private/var/folders/j9/7ytknchx3lj82tlj2tlszm5c0000gn/T/pip-build-env-j0pur41a/overlay/lib/python3.12/site-packages/setuptools/config/pyprojecttoml.py", line 60, in validate
          raise ValueError(f"{error}\n{summary}") from None
      ValueError: invalid pyproject.toml config: `tool.setuptools.package-data`.
      configuration error: `tool.setuptools.package-data` keys must be named by:
      
          at least one of the following:
            - {type: string, format: 'python-module-name'}
            - {predefined value: '*'}
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**To Reproduce**
1. I just ran "pip install git+https://github.com/Storia-AI/sage.git@main" and it produced the above message

**Expected behavior**
I expected to be able to install the project

**Screenshots**

**Setup (please complete the following information):**
 - Python version: [e.g. 3.12.6]
 - OS: [e.g. MacOS]

**Additional context**

**Comment by iuliaturc** [comment]
Ah good catch, looks like we made a mistake when switching to project.toml.
@mikelueck I submitted [this fix](https://github.com/Storia-AI/sage/commit/97df853c4a498c03a5ed015a435315a3939e4345), would you mind trying again to confirm it's fixed?
